version: "3.7"

services:
    my-backend: 
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./index.js:/myfolder/index.js
            - ./certification.js:/myfolder/certification.js
            - ./opengraph.js:/myfolder/opengraph.js
        ports:
            - 3000:3000

    my-database:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports:
            - 27017:27017